services:
    db:
        container_name: db
        image: postgres:15-alpine
        volumes:
            - ./db:/var/lib/postgresql/data
        env_file:
            - .env

    web:
        container_name: web
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/opt/app
            - ./media:/opt/app/media
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db
